# Generated by Django 6.0.1 on 2026-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_audio_file_alter_exam_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الامتحان'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم الامتحان'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='questions_audio/', verbose_name='ملف الصوت'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتيب السؤال'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='audio_answer',
            field=models.FileField(upload_to='answers/%Y/%m/%d/'),
        ),
    ]
