# Generated by Django 6.0.1 on 2026-01-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_description_alter_exam_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='exams_audio/', verbose_name='ملف صوت التعريف'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='questions_audio/', verbose_name='ملف صوت السؤال'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='audio_answer',
            field=models.FileField(upload_to='answers/%Y/%m/%d/', verbose_name='ملف الإجابة'),
        ),
    ]
