# Generated by Django 6.0.1 on 2026-01-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_audio_file_alter_question_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='short_audio',
            field=models.FileField(blank=True, null=True, upload_to='exams_audio/short/', verbose_name='ملف القائمة المختصر'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='exams_audio/', verbose_name='ملف الترحيب والتعليمات'),
        ),
    ]
