# Generated by Django 6.0.1 on 2026-01-10 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_short_audio_alter_exam_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الدورة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدورة')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='courses_icons/', verbose_name='صورة/أيقونة الدورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='courses_audio/', verbose_name='صوت تعريف الدورة')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب الدرس')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lessons_audio/', verbose_name='صوت عنوان الدرس')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='exams.course', verbose_name='الدورة التابعة لها')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب الخطوة')),
                ('segment_type', models.CharField(choices=[('LECTURE', 'شرح صوتي فقط'), ('SIMULATOR', 'محاكاة (انتظار ضغط زر)'), ('VOICE_Q', 'سؤال وتسجيل صوتي'), ('FILE_UPLOAD', 'رفع ملف (مستقبلي)')], default='LECTURE', max_length=20, verbose_name='نوع الخطوة')),
                ('text', models.TextField(verbose_name='نص الشرح/السؤال')),
                ('error_text', models.TextField(blank=True, help_text='هذا النص سيقرؤه النظام إذا أخطأ الطالب.', null=True, verbose_name='رسالة الخطأ/التوضيح')),
                ('expected_key', models.CharField(blank=True, help_text='مثال: Space, Enter, KeyC', max_length=50, null=True, verbose_name='زر الكيبورد المتوقع')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='segments_audio/', verbose_name='ملف الصوت الأساسي')),
                ('error_audio_file', models.FileField(blank=True, null=True, upload_to='segments_audio/errors/', verbose_name='ملف صوت الخطأ')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='exams.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
